Started by upstream project "[8mha:////4HtKCWQZHj2Fg9kWDzhFG9eQr4yXLBVpt8RgTlUsMse+AAAAnx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzeEgZh/az8JP1AR/+A4PiAovys1OQSfQAX9RkJyAAAAA==[0mQAOPS_Project" build number [8mha:////4BtoBtVcBn18OVl/iEf5aW4h1oBvRK5CV47R5zUlJnLAAAAAoR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAymEgZR/az8JP1AR/+A4PiAovys1OQSfUMjAE76rRfKAAAA[0m12
originally caused by:
 Started by user [8mha:////4FAMTZcYqTXXPDWs2xVOd5xq3rAhxp/QA4cL7iSsKXpAAAAAmB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAy+EgYe/dLi1CL93MSM3NIUAEa5nOTBAAAA[0mMahmudul Islam
Running as SYSTEM
Building in workspace D:\Jenkins\Jenkins_Home\.jenkins\workspace\Test_QAOPS_project
[Test_QAOPS_project] $ cmd /c call C:\Users\SJDHAK~1.DES\AppData\Local\Temp\jenkins5345770329213390200.bat

D:\Jenkins\Jenkins_Home\.jenkins\workspace\Test_QAOPS_project>cd D:\QAOPS_DEMO\Test_Demo 

D:\QAOPS_DEMO\Test_Demo>python -m pytest tests\test_greeting_page.py --html=report.html 
============================= test session starts =============================
platform win32 -- Python 3.12.0, pytest-7.4.3, pluggy-1.3.0
rootdir: D:\QAOPS_DEMO\Test_Demo
plugins: html-4.1.0, metadata-3.0.0
collected 3 items

tests\test_greeting_page.py .F.                                          [100%]

================================== FAILURES ===================================
_____ test_greeting_page[-file:///D:/QAOPS_DEMO/Website_demo/index.html] ______

browser = <selenium.webdriver.chrome.webdriver.WebDriver (session="edf1170450a7b6e57dff0e686c3b8f3e")>
url = 'file:///D:/QAOPS_DEMO/Website_demo/index.html', name = ''

    @pytest.mark.parametrize("url", ["file:///D:/QAOPS_DEMO/Website_demo/index.html",])
    @pytest.mark.parametrize("name", ["John", "", "Jack",])
    def test_greeting_page(browser, url, name):
        greeting_actions = GreetingActions(browser)
    
        greeting_actions.get_to_page(url)
        time.sleep(2)
    
        greeting_actions.submit_name(name)
        time.sleep(2)
    
        actual_greeting = greeting_actions.get_greeting()
        expected_greeting = f"Hello, {name}!"
    
        if name != "":
            assert actual_greeting == expected_greeting
        else:
>           assert actual_greeting == "" or expected_greeting != "Hello, !"
E           AssertionError: assert ('Hello, !' == ''
E             + Hello, ! or 'Hello, !' != 'Hello, !')

tests\test_greeting_page.py:34: AssertionError
----- Generated html report: file:///D:/QAOPS_DEMO/Test_Demo/report.html ------
=========================== short test summary info ===========================
FAILED tests/test_greeting_page.py::test_greeting_page[-file:///D:/QAOPS_DEMO/Website_demo/index.html] - AssertionError: assert ('Hello, !' == ''
  + Hello, ! or 'Hello, !' != 'Hello, !')
======================== 1 failed, 2 passed in 35.59s =========================

D:\QAOPS_DEMO\Test_Demo>exit 1 
Build step 'Execute Windows batch command' marked build as failure
Triggering a new build of [8mha:////4CQapgyja/k6tzs45BA7NBwdu9QvhPTKGP09im+Coha1AAAAsh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyFEgY1/az8JP1AR/+A4PiAovys1OSS+JDU4pL4oNSC/KKS+NCCnPzEFH0AO5Ij7dsAAAA=[0mQAOPS_Project_Test_Report_Upload
Finished: FAILURE
