Started by upstream project "[8mha:////4HkCynrRPtWbIWnaieoKcPJ7epWBAZQBdhIFkqWRrk1pAAAApB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyhEgYJ/az8JP2Q1OKS+EBH/4Dg+IKi/KzU5BJ9AKf9N3nNAAAA[0mTest_QAOPS_project" build number [8mha:////4Gjve64v9MMcbirTD7UJhuzUDyPNBf/ErcQkqj7/ruA8AAAAph+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAymEgYp/az8JP2Q1OKS+EBH/4Dg+IKi/KzU5BJ9IxMAA2WjAs8AAAA=[0m24
originally caused by:
 Started by user [8mha:////4FAMTZcYqTXXPDWs2xVOd5xq3rAhxp/QA4cL7iSsKXpAAAAAmB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAy+EgYe/dLi1CL93MSM3NIUAEa5nOTBAAAA[0mMahmudul Islam
Running as SYSTEM
Building in workspace D:\Jenkins\Jenkins_Home\.jenkins\workspace\QAOPS_Project_Test_Report_Upload
[QAOPS_Project_Test_Report_Upload] $ cmd /c call C:\Users\SJDHAK~1.DES\AppData\Local\Temp\jenkins6922159646599119795.bat

D:\Jenkins\Jenkins_Home\.jenkins\workspace\QAOPS_Project_Test_Report_Upload>cd D:\QAOPS_DEMO\Test_Demo\ 

D:\QAOPS_DEMO\Test_Demo>git branch temp 

D:\QAOPS_DEMO\Test_Demo>git add report.html 

D:\QAOPS_DEMO\Test_Demo>git commit -m "update new report"  
[detached HEAD 1abf31e] update new report
 1 file changed, 3 insertions(+), 3 deletions(-)

D:\QAOPS_DEMO\Test_Demo>git checkout main 
M	Test_Demo/tests/__pycache__/test_greeting_page.cpython-312-pytest-7.4.3.pyc
M	Test_Demo/tests/pages/__pycache__/greeting_actions.cpython-312.pyc
Your branch and 'origin/main' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" if you want to integrate the remote branch with yours)
Warning: you are leaving 1 commit behind, not connected to
any of your branches:

  1abf31e update new report

If you want to keep it by creating a new branch, this may be a good time
to do so with:

 git branch <new-branch-name> 1abf31e

Switched to branch 'main'

D:\QAOPS_DEMO\Test_Demo>git merge temp 
Auto-merging Test_Demo/report.html
CONFLICT (content): Merge conflict in Test_Demo/report.html
Automatic merge failed; fix conflicts and then commit the result.

D:\QAOPS_DEMO\Test_Demo>git push origin main 
To https://github.com/mahmud-i/QAOPS_DEMO_Task.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/mahmud-i/QAOPS_DEMO_Task.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

D:\QAOPS_DEMO\Test_Demo>git branch -D temp 
Deleted branch temp (was e9cf28a).

D:\QAOPS_DEMO\Test_Demo>exit 0 
Finished: SUCCESS
